### ISSUE TITLE
Roadmap for v3

### ISSUE THREAD

**Issue by gregorypratt** [RiotGear/rg#66]
- [x] Switch callbacks to events: https://github.com/RiotGear/rg/issues/64
- [x] Release v1.0.0 of rg-css: https://github.com/RiotGear/rg-css
- [x] Decouple the tags: https://github.com/RiotGear/rg/issues/59
- [x] Re-evaluate the tag's CSS based on rg-css
- [x] Clean global namespace by adding classes to the `rg` object: #74 (removed them)

Note: [rg](https://github.com/RiotGear/rg) and [rg-css](https://github.com/RiotGear/rg-css) will be standalone entities but will be compatible when used together
